#!/bin/bash
#set -eu

# Charge les fonctions génériques habituellement utilisées dans le script
#source fonctions

# Active trap pour arrêter le script si une erreur est détectée.
#TRAP_ON

# Source app helpers
source /usr/share/yunohost/helpers

# We retrieve app parameters
app=$YNH_APP_INSTANCE_NAME

# We check variables are not empty

CHECK_VAR () {  # Vérifie que la variable n'est pas vide.
# $1 = Variable à vérifier
# $2 = Texte à afficher en cas d'erreur
        test -n "$1" || (echo "$2" >&2 && false)
}
CHECK_VAR "$app" "app name not set"

path=$(ynh_app_setting_get $app path)
domain=$(ynh_app_setting_get $app domain)
final_path=$(ynh_app_setting_get $app final_path)
finalnginxconf=$(ynh_app_setting_get $app finalnginxconf)
finalphpconf=$(ynh_app_setting_get $app finalphpconf)
runninguser=$app-ynh

# Suppression du dossier de la webapp
sudo rm -rf $final_path

# Suppression de la config nginx de la webapp
sudo rm -f $finalnginxconf
sudo rm -f $finalphpconf

# Remove app dependencies
if ynh_package_is_installed "cops-deps"; then
  ynh_package_autoremove "cops-deps"
fi

# Remove the user account
id "$runninguser" >/dev/null 2>&1 \
&& sudo deluser --quiet --remove-home "$runninguser" >/dev/null

# We reload the services
sudo service php5-fpm reload
sudo service nginx reload
sudo yunohost app ssowatconf
