#!/bin/bash
set -u

# Charge les fonctions génériques habituellement utilisées dans le script
SECURE_REMOVE () {      # Suppression de dossier avec vérification des variables
        chaine="$1"     # L'argument doit être donné entre quotes simple '', pour éviter d'interpréter les variables.
        no_var=0
        while (echo "$chaine" | grep -q '\$')   # Boucle tant qu'il y a des $ dans la chaine
        do
                no_var=1
                global_var=$(echo "$chaine" | cut -d '$' -f 2)  # Isole la première variable trouvée.
                only_var=\$$(expr "$global_var" : '\([A-Za-z0-9_]*\)')  # Isole complètement la variable en ajoutant le $ au début et en gardant uniquement le nom de la variable. Se débarrasse$
                real_var=$(eval "echo ${only_var}")             # `eval "echo ${var}` permet d'interpréter une variable contenue dans une variable.
                if test -z "$real_var" || [ "$real_var" = "/" ]; then
                        echo "Variable $only_var is empty, suppression of $chaine cancelled." >&2
                        return 1
                fi
                chaine=$(echo "$chaine" | sed "s@$only_var@$real_var@") # remplace la variable par sa valeur dans la chaine.
        done
        if [ "$no_var" -eq 1 ]
        then
                if [ -e "$chaine" ]; then
                        echo "Delete directory $chaine"
                        sudo rm -r "$chaine"
                fi
                return 0
        else
                echo "No detected variable." >&2
                return 1
        fi
}

REMOVE_SYS_USER () {   # Supprime l'utilisateur système dédié à l'app
    if ynh_system_user_exists "$1"    # Test l'existence de l'utilisateur
    then
        sudo userdel $1
    fi
}

# Active trap pour arrêter le script si une erreur est détectée.

# Source app helpers
source /usr/share/yunohost/helpers

# We retrieve app parameters
app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
finalnginxconf=$(ynh_app_setting_get $app finalnginxconf)
finalphpconf=$(ynh_app_setting_get $app finalphpconf)
runninguser=$app-ynh

# Suppression du dossier de la webapp
SECURE_REMOVE   '$final_path'

# Suppression de la config nginx de la webapp
if [ -e "$finalnginxconf" ]; then # Delete nginx config
	echo "Delete nginx config"
	sudo rm $finalnginxconf
fi

if [ -e "$finalphpconf" ]; then # Delete nginx config
	echo "Delete php-fpm config"
	sudo rm $finalphpconf
fi

# Remove app dependencies
if ynh_package_is_installed "cops-deps"; then
  ynh_remove_app_dependencies
fi

# Remove the user account~
#id "$runninguser" >/dev/null 2>&1 \
#&& sudo deluser --quiet "$runninguser" >/dev/null
REMOVE_SYS_USER "$runninguser"

# We reload the services
sudo service php7.0-fpm reload
sudo service nginx reload
sudo yunohost app ssowatconf
