#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
#set -eu

#TRAP_ON () {    # Activate signal capture
#        trap EXIT_PROPERLY ERR  # Capturing ex it signals on error
#}

# Active trap pour arrêter le script si une erreur est détectée.
#TRAP_ON

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve old app settings
final_path=$(ynh_app_setting_get $app final_path)
path=$(ynh_app_setting_get $app path)
domain=$(ynh_app_setting_get $app domain)
is_public=$(ynh_app_setting_get $app is_public)
finalnginxconf=$(ynh_app_setting_get $app finalnginxconf)
finalphpconf=$(ynh_app_setting_get $app finalphpconf)
runninguser=$(ynh_app_setting_get $app runninguser)
basicauthcreate=$(ynh_app_setting_get $app basicauthcreate)

# We install dependencies
sudo apt-get update -y
sudo apt-get install php5-gd php5-sqlite php5-json php5-intl -y

# Restore sources & data
sudo mkdir -p $final_path
sudo cp -a ./sources/* $final_path/

# Restore permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R $runninguser:$runninguser $final_path

if [ "$basicauthcreate" = "Yes" ];
then
        sudo chmod 440 $final_path/htpasswd
        sudo chown www-data:www-data $final_path/htpasswd
else
        echo "Nothing to do"
fi

# Restore NGINX configuration
sudo cp -a ./nginx.conf $finalnginxconf

### PHP (remove if not used) ###
# If a dedicated php-fpm process is used:
# # Copy PHP-FPM pool configuration and reload the service
sudo cp -a ./php-fpm.conf $finalphpconf
### PHP end ###

# Make app public if necessary
is_public=$(ynh_app_setting_get $app is_public)
if [ "$is_public" = "Yes" ];
then
        ynh_app_setting_set $app skipped_uris "/"
else
        ynh_app_setting_set $app protected_uris "/"
fi


# Restart webserver
sudo service nginx reload
sudo service php5-fpm reload
sudo yunohost app ssowatconf

