#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Creating a calibre directory..."

# build multimedia directory
ynh_multimedia_build_main_dir
ynh_multimedia_addaccess "$app"

calibre_dir="/home/yunohost.multimedia/share/eBook"
ynh_app_setting_set --key=calibre_dir --value=$calibre_dir

# Check if metadata.db file exists. If not create it (empty library)
if [ ! -e "$calibre_dir/metadata.db" ]; then
    cp -a ../conf/metadata.db.empty "$calibre_dir/metadata.db"
fi

chmod 750 "$calibre_dir"
chmod -R o-rwx "$calibre_dir"
chown -R $app:www-data "$calibre_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

timezone="$(timedatectl show --value --property=Timezone)"

ynh_config_add --template="config_local.php" --destination="$install_dir/config_local.php"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading $app's service..."

ynh_systemctl --service=php$php_version-fpm --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
